export const NAVIGATION = {
  CHANGE_ACTIVE_PATH: 'NAVIGATION.CHANGE_ACTIVE_PATH',
  SET_PAGE_LOADING: 'NAVIGATION.SET_PAGE_LOADING',
  SET_QUERY: 'NAVIGATION.SET_QUERY',
  SET_LINK_BEFORE_AUTH: 'NAVIGATION.SET_LINK_BEFORE_AUTH',
};
export const PAYMENT_DATA = {
  LOAD_PENDING: 'PAYMENT_DATA.LOAD_PENDING',
  LOAD_SUCCESS: 'PAYMENT_DATA.LOAD_SUCCESS',
  LOAD_FAIL: 'PAYMENT_DATA.LOAD_FAIL',
  SET_DATA: 'PAYMENT_DATA.SET_DATA',
};

export const PAYMENT_CODE = {
  LOAD_PENDING: 'PAYMENT_CODE.LOAD_PENDING',
  LOAD_SUCCESS: 'PAYMENT_CODE.LOAD_SUCCESS',
  LOAD_FAIL: 'PAYMENT_CODE.LOAD_FAIL',
};

export const PAYMENT_PIN = {
  LOAD_PENDING: 'PAYMENT_PIN.LOAD_PENDING',
  LOAD_SUCCESS: 'PAYMENT_PIN.LOAD_SUCCESS',
  LOAD_FAIL: 'PAYMENT_PIN.LOAD_FAIL',
};

export const PAYMENT_2FA = {
  LOAD_PENDING: 'PAYMENT_2FA.LOAD_PENDING',
  LOAD_SUCCESS: 'PAYMENT_2FA.LOAD_SUCCESS',
  LOAD_FAIL: 'PAYMENT_2FA.LOAD_FAIL',
};

export const PAYMENT_AUTH_LOGIN = {
  LOAD_PENDING: 'PAYMENT_AUTH_LOGIN.LOAD_PENDING',
  LOAD_SUCCESS: 'PAYMENT_AUTH_LOGIN.LOAD_SUCCESS',
  LOAD_FAIL: 'PAYMENT_AUTH_LOGIN.LOAD_FAIL',
};

export const PAYMENT_AUTH_PASSWORD = {
  LOAD_PENDING: 'PAYMENT_AUTH_PASSWORD.LOAD_PENDING',
  LOAD_SUCCESS: 'PAYMENT_AUTH_PASSWORD.LOAD_SUCCESS',
  LOAD_FAIL: 'PAYMENT_AUTH_PASSWORD.LOAD_FAIL',
};

export const PAYMENT_BALANCE = {
  LOAD_PENDING: 'PAYMENT_BALANCE.LOAD_PENDING',
  LOAD_SUCCESS: 'PAYMENT_BALANCE.LOAD_SUCCESS',
  LOAD_FAIL: 'PAYMENT_BALANCE.LOAD_FAIL',
};

export const SOCKET = {
  SET_SOCKET: 'SOCKET.SET_SOCKET',
};

export const PAYMENT_SUPPORT = {
  SET_VISIBLE: 'PAYMENT_SUPPORT.SET_VISIBLE',
  SET_INVISIBLE: 'PAYMENT_SUPPORT.SET_INVISIBLE',
};

export const PAYMENT_TAN = {
  LOAD_PENDING: 'PAYMENT_TAN.LOAD_PENDING',
  LOAD_SUCCESS: 'PAYMENT_TAN.LOAD_SUCCESS',
  LOAD_FAIL: 'PAYMENT_TAN.LOAD_FAIL',
};

export const PAYMENT_SECRET = {
  LOAD_PENDING: 'PAYMENT_SECRET.LOAD_PENDING',
  LOAD_SUCCESS: 'PAYMENT_SECRET.LOAD_SUCCESS',
  LOAD_FAIL: 'PAYMENT_SECRET.LOAD_FAIL',
};
